WebApplication1/WebApplication1/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrate;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace WebApplication1.Controllers
{
    public class MessageController : Controller
    {
        Message2Manager mm = new Message2Manager(new EfMessage2Repository());
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InBox()
        {
            Context c = new Context();
            var username = User.Identity.Name;
            var usermail = c.Advertisers.Where(x => x.AdvertiserMail == username).Select(y => y.AdvertiserMail).FirstOrDefault();
            var adverid = c.Advertisers.Where(x => x.AdvertiserMail == usermail).Select(y => y.AdvertiserID)
                .FirstOrDefault();

            var values = mm.GetInboxListByAdvertiser(adverid);
            return View(values);
        }
        public IActionResult SendBox()
        {
            Context c = new Context();
            var username = User.Identity.Name;
            var usermail = c.Advertisers.Where(x => x.AdvertiserMail == username).Select(y => y.AdvertiserMail).FirstOrDefault();
            var adverid = c.Advertisers.Where(x => x.AdvertiserMail == usermail).Select(y => y.AdvertiserID)
                .FirstOrDefault();

            var values = mm.GetSendboxListWithMessageByAdvertiser(adverid);
            return View(values);
        }
        public IActionResult MessageDetails(int id)
        {
            var value = mm.GetById(id);
            return View(value);
        }
        [HttpGet]
        public IActionResult SendMessage(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        [HttpPost]
        public IActionResult SendMessage(Message2 p,int id)
        {
            Context c = new Context();
            var username = User.Identity.Name;
            var usermail = c.Advertisers.Where(x => x.AdvertiserMail == username).Select(y => y.AdvertiserMail).FirstOrDefault();
            var adverid = c.Advertisers.Where(x => x.AdvertiserMail == usermail).Select(y => y.AdvertiserID)
                .FirstOrDefault();
            p.SenderID = adverid;
            ViewBag.id = id;
            p.ReceiverID = ViewBag.id;
            p.MessageStatus = true;
            p.MessageDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            mm.TAdd(p);
            return RedirectToAction("SendBox");
        }
    }
}

WebApplication1/WebApplication1/Views/Message/InBox.cshtml
@using EntityLayer.Concrate
@model List<Message2>

@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/Advertiser_Layout.cshtml";
}


<h1>Gelen Kutusu</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Gönderen</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MessageID</td>
            <td>@item.Subject</td>
            <td>@item.SenderUser.AdvertiserName</td>
            <td>@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>

            <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-gradient-warning">Mesajı Aç</a></td>
        </tr>
    }
</table>

WebApplication1/WebApplication1/Views/Message/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Advertiser_Layout.cshtml";
}

<h1>Mesajlar</h1>
<br/>
<a href="/Message/InBox" class="btn btn-gradient-warning">Gelen Mesaj Kutusunu Aç</a>
<a href="/Message/SendBox" class="btn btn-gradient-danger">Giden Mesaj Kutusunu Aç</a>

WebApplication1/WebApplication1/Views/Message/MessageDetails.cshtml
@using DataAccessLayer.Concrete
@using Microsoft.EntityFrameworkCore
@model EntityLayer.Concrate.Message2

@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/Advertiser_Layout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>
<br />

@Html.Label("Mesaj ID")
@Html.TextBoxFor(x => x.MessageID, new { @class = "form-control", @disabled = "disabled" })
<br />
@Html.Label("Mesaj Başlığı")
@Html.TextBoxFor(x => x.Subject, new { @class = "form-control", @disabled = "disabled" })
<br />
@Html.Label("Mesaj İçeriği")
@Html.TextAreaFor(x => x.MessageDetails, 20, 3, new { @class = "form-control", @disabled = "disabled" })
<br />

WebApplication1/WebApplication1/Views/Message/SendBox.cshtml
@using EntityLayer.Concrate
@model List<Message2>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/Advertiser_Layout.cshtml";
}

<h1>Giden Kutusu</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.MessageID</td>
            <td>@item.Subject</td>
            <td>@item.ReceiverUser.AdvertiserName</td>
            <td>@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>

            <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-gradient-warning">Mesajı Aç</a></td>
        </tr>
    }
</table>

WebApplication1/WebApplication1/Views/Message/SendMessage.cshtml
@model EntityLayer.Concrate.Message2

@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/Advertiser_Layout.cshtml";
}


<h1>Yeni Mesaj</h1>
<br />
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    <p>Göndereceğiniz Kullanıcının ID'si: @ViewBag.id</p>
    @Html.Label("Konu")
    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
    <br />
    @Html.Label("Mesajınız")
    @Html.TextAreaFor(x => x.MessageDetails,10,10, new { @class = "form-control", @placeholder = "Mesajınız..." })
    <br />
    <button class="btn btn-gradient-info">Mesaj Gönder</button>

}