WebApplication1/WebApplication1/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrate;
using Microsoft.AspNetCore.Mvc;
using System;

namespace WebApplication1.Controllers
{
    public class CommentController : Controller
    {
        CommentManager cm = new CommentManager((new EfCommentRepository()));

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult PartialAddComment()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult PartialAddComment(Comment c, int id)
        {
            c.CommentDate = DateTime.Now;
            c.CommentStatus = true;
            c.EstateID = id;
            cm.CommentAdd(c);

            // Yorum ekledikten sonra kullanıcıyı ilgili ilanın sayfasına yönlendirin.
            return RedirectToAction("EstateReadAll", "Estate", new { id = id });
        }
        public PartialViewResult CommentListByEstate(int id)
        {
            var values = cm.GetList(id);
            return PartialView(values);
        }
    }
}

WebApplication1/WebApplication1/Views/Comment/CommentListByEstate.cshtml
@model IEnumerable<EntityLayer.Concrate.Comment>
<div class="comment-top">
	<h4>Yorumlar</h4>
	<div class="media">
		<img src="~/CoreBlogTema//web/images/t1.jpg" alt="" class="img-fluid" />
		<div class="media-body">
			<h5 class="mt-0">Joseph Goh</h5>
			<p>
				Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
				Cras a ornare elit.
			</p>

			<div class="media mt-3">
				<a class="d-flex pr-3" href="#">
					<img src="images/t2.jpg" alt="" class="img-fluid" />
				</a>
				<div class="media-body">
					<h5 class="mt-0">Richard Spark</h5>
					<p>
						Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
						Cras a ornare elit.
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

WebApplication1/WebApplication1/Views/Comment/PartialAddComment.cshtml
<div class="comment-top">
    <h4>Bir Yorum Yapın</h4>
    <div class="comment-bottom">
        <form asp-action="PartialAddComment" asp-controller="Comment" method="post">
            <input type="hidden" name="id" value="@ViewBag.ItemID" /><br/>
            <input class="form-control" type="text" name="CommentUserName" placeholder="Adınız Soyadınız" required="">
            <input class="form-control" type="text" name="CommentTitle" placeholder="Konu" required="">
            <input class="form-control" type="text" name="EstateScore" placeholder="İlana Puanınız" required="">
            <input class="form-control" name="CommentContent" placeholder="Bir mesaj bırakın..." required=""></input><br />
            <button type="submit" class="btn btn-primary submit">Yorum Yap</button>
        </form>
    </div>
</div>